// tslint:disable
/**
 * Bananotes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Position } from './position';
import { Size } from './size';

/**
 *
 * @export
 * @interface Entry
 */
export interface Entry {
  /**
   *
   * @type {string}
   * @memberof Entry
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof Entry
   */
  author: string;
  /**
   *
   * @type {string}
   * @memberof Entry
   */
  content: string;
  /**
   *
   * @type {string}
   * @memberof Entry
   */
  url: string;
  /**
   *
   * @type {Size}
   * @memberof Entry
   */
  size: Size;
  /**
   *
   * @type {Position}
   * @memberof Entry
   */
  position: Position;
  /**
   * user likes count
   * @type {number}
   * @memberof Entry
   */
  likes: number;
  /**
   *
   * @type {number}
   * @memberof Entry
   */
  dislikes: number;
  /**
   *
   * @type {number}
   * @memberof Entry
   */
  createTime: number;
  /**
   *
   * @type {number}
   * @memberof Entry
   */
  updateTime: number;
  /**
   *
   * @type {boolean}
   * @memberof Entry
   */
  isDeleted: boolean;
}
