// tslint:disable
/**
 * Bananotes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EntryPosition } from './entry-position';
import { EntrySize } from './entry-size';

/**
 *
 * @export
 * @interface InlineObject1
 */
export interface InlineObject1 {
  /**
   *
   * @type {string}
   * @memberof InlineObject1
   */
  entryId: string;
  /**
   *
   * @type {string}
   * @memberof InlineObject1
   */
  content: string;
  /**
   *
   * @type {EntryPosition}
   * @memberof InlineObject1
   */
  position: EntryPosition;
  /**
   *
   * @type {EntrySize}
   * @memberof InlineObject1
   */
  size: EntrySize;
}
