// tslint:disable
/**
 * Bananotes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {
  /**
   * ID
   * @type {string}
   * @memberof InlineResponse200
   */
  id: string;
  /**
   * entries array
   * @type {Array<string>}
   * @memberof InlineResponse200
   */
  entries: Array<string>;
  /**
   * entries array
   * @type {Array<string>}
   * @memberof InlineResponse200
   */
  invisibleEntries: Array<string>;
  /**
   * create Time
   * @type {string}
   * @memberof InlineResponse200
   */
  createdTime: string;
  /**
   * update Time
   * @type {string}
   * @memberof InlineResponse200
   */
  updatedTime: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse200
   */
  userId: string;
}
