// tslint:disable
/**
 * Bananotes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface InlineResponse2004
 */
export interface InlineResponse2004 {
  /**
   *
   * @type {string}
   * @memberof InlineResponse2004
   */
  message: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse2004
   */
  id: string;
  /**
   *
   * @type {boolean}
   * @memberof InlineResponse2004
   */
  isDeleted: boolean;
}
