// tslint:disable
/**
 * Bananotes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EntryPosition } from './entry-position';
import { EntrySize } from './entry-size';

/**
 *
 * @export
 * @interface InlineResponse2003
 */
export interface InlineResponse2003 {
  /**
   *
   * @type {string}
   * @memberof InlineResponse2003
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse2003
   */
  author: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse2003
   */
  content: string;
  /**
   *
   * @type {EntryPosition}
   * @memberof InlineResponse2003
   */
  position: EntryPosition;
  /**
   *
   * @type {EntrySize}
   * @memberof InlineResponse2003
   */
  size: EntrySize;
  /**
   *
   * @type {string}
   * @memberof InlineResponse2003
   */
  url: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse2003
   */
  createTime: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse2003
   */
  updateTime: string;
  /**
   *
   * @type {boolean}
   * @memberof InlineResponse2003
   */
  isDeleted: boolean;
}
